### ISSUE TITLE
Problème UpdateContact

### ISSUE THREAD

**Issue by XavierBorelly** [bewizyu/familink-api#15]
Quand on update un utilisateur via PostMan (ou le code d'ailleurs), on ce retrouve avec des champs de l'utilisateur qui on disparus (en l'occurence les champs : Phone, profiles, isFamilinkUser, isEmergencyUser), voila un exemple des contacts de l'utilisateur 0600000002 : 

{
        "_id": "599fd895d32e7008358df5d9",
        "gravatar": "https://www.gravatar.com/avatar/78b1c0e2dd92f3fba4e2e0ed8bb2f913",
        "email": "Update@email.com",
        "lastName": "trUpdate",
        "firstName": "test54Update"
},
{
        "phone": "0668238369",
        "firstName": "Rosa",
        "lastName": "Scott",
        "email": "kij@zeset.gov",
        "profile": "SENIOR",
        "gravatar": "https://www.gravatar.com/avatar/2ff600ae6cc3e7c88baa7457a4168909",
        "isFamilinkUser": true,
        "isEmergencyUser": false,
        "_id": "5996f1fb482a590826eae6fd"
}

**Comment by nartawak** [comment]
@XavierBorelly est-ce que tu peux me donner un exemple des paramètres que tu envoies dans la requête. Merci

**Comment by XavierBorelly** [comment]
{
   "phone": "0708091011",
   "firstName": "test54Update",
   "lastName": "trUpdate",
   "email": "Update@email.com",
   "gravatar" : "https://www.gravatar.com/avatar/78b1c0e2dd92f3fba4e2e0ed8bb2f913"
}

**Comment by nartawak** [comment]
@XavierBorelly Je viens de déployer une version. Valide que c'est bien corrigé et ferme l'issue si c'est OK

**Comment by XavierBorelly** [comment]
Correction validé!
