### ISSUE TITLE
Souci sur le getUser

### ISSUE THREAD

**Issue by lenteurman** [bewizyu/familink-api#16]
Sur postman on n'a pas de GET pour récupérer les informations d'un user.
Le body est mis dans un PUT , mais pas dans un GET. Du coup, il me semble pas possible de pouvoir récupérer ce body.

La fonction me semble primordiale, car on ne peut pas faire de l'Async Storage si l'user se connecte avec un autre téléphone

**Comment by nartawak** [comment]
@lenteurman je viens de pousser une PR qui va être déployée dans quelques minutes. Je te laisse valider et clore cette issue si tut est OK pour toi

**Comment by lenteurman** [comment]
Je récupère bien le body dans ma Promise. Je peux ainsi récupérer mon utilisateur authentifié.
Le problème a été réglé.
Merci.
